---

- name: add googlechrome apt key
  ansible.builtin.apt_key:
    url: "{{ googlechrome_apt_key_url }}"
    keyring: "{{ googlechrome_apt_key_keyring }}"

- name: add google chrome repo
  ansible.builtin.apt_repository:
    repo: "{{ googlechrome_repo }}"
    state: present
    filename: google-chrome

- name: install latest google chrome
  ansible.builtin.apt:
    name: google-chrome-stable
    force_apt_get: yes

...
