---

- name: add vscode repo
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
    filename: vscode

- name: install latest visual studio code
  apt:
    name: code
    force_apt_get: yes

- name: install some popular vscode extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

...
