---

hashicorp_repo_jammy: "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main"  # ubuntu 22.04
hashicorp_apt_key_url: "https://apt.releases.hashicorp.com/gpg"
hashicorp_apt_key_keyring: "/etc/apt/trusted.gpg.d/hashicorp.gpg"

hashicorp_packages:
  - vagrant
  - terraform
  - packer

...
