---

vscode_repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
vscode_apt_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
vscode_apt_key_keyring: "/etc/apt/trusted.gpg.d/microsoft.gpg"

vscode_extensions:
  - aaron-bond.better-comments
  - formulahendry.code-runner
  - donjayamanne.githistory
  - eamodio.gitlens
  - golang.Go
  - vincaslt.highlight-matching-tag
  - oderwat.indent-rainbow
  - yzhang.markdown-all-in-one
  - ms-python.python
  - ms-python.vscode-pylance
  - humao.rest-client
  - Gruntfuggly.todo-tree
  - shardulm94.trailing-spaces
  - vscodevim.vim
  - visualstudioexptteam.vscodeintellicode
  - ms-azuretools.vscode-docker
  - vscode-icons-team.vscode-icons
  - esbenp.prettier-vscode
  - redhat.vscode-yaml
  - danielroedl.meld-diff
  - davidanson.vscode-markdownlint
  - hashicorp.terraform
  - gera2ld.markmap-vscode  # create mindmap from markdown file
  - terrastruct.d2  # diagram scripting language that turns text to diagrams
  - rangav.vscode-thunder-client  # lightweight rest client for testing APIs
  - redhat.ansible  # ansible extension
  - timonwong.shellcheck  # shellcheck linter for sh/bash/dash/ksh scripts
  - Catppuccin.catppuccin-vsc  # Catppuccin theme
  - Catppuccin.catppuccin-vsc-icons  # Catppuccin icons
  - bierner.markdown-mermaid  # markdown preview mermaid support
#  - rust-lang.rust-analyzer  # rust linter

...
