---

- name: install zsh and other related packages
  apt:
    name: "{{ zsh_packages }}"
    state: latest

- name: change user's shell to zsh
  user:
    name: "{{ local_username }}"
    shell: /bin/zsh

- name: install antigen
  git:
    dest: "~{{ local_username }}/.antigen"
    repo: "{{ zsh_antigen_url }}"
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: create local fonts directory
      file:
        path: "~{{ local_username }}/.local/share/fonts"
        state: directory
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: download adobe source code pro fonts (1/3)
      get_url:
        dest: /tmp
        url: "{{ zsh_adobe_source_code_pro_font_url }}"

    - name: extract adobe source code pro fonts (2/3)
      unarchive:
        src: "/tmp/{{ zsh_adobe_source_code_pro_font_file }}"
        dest: /tmp

    - name: copy adobe source code pro fonts to fonts folder (3/3)
      copy:
        src: "/tmp/{{ zsh_adobe_source_code_pro_font_dir }}/OTF/"
        dest: "~{{ local_username }}/.local/share/fonts/"

  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: get the powerline patched fonts (1/2)
      git:
        dest: "/tmp/{{ zsh_powerline_font_dir }}"
        repo: "{{ zsh_powerline_font_url }}"
        update: yes

    - name: install the powerline patched fonts (2/2)
      shell: ./install.sh
      args:
        chdir: "/tmp/{{ zsh_powerline_font_dir }}"

  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: get the awesome fonts (1/2)
      git:
        repo: "{{ zsh_awesome_font_url }}"
        version: "{{ zsh_awesome_font_git_version }}"
        dest: "/tmp/{{ zsh_awesome_font_dir }}"
        update: yes

    - name: copy the awesome fonts (2/2)
      copy:
        src: "{{ item }}"
        dest: "~{{ local_username }}/.local/share/fonts/"
      with_fileglob:
        - "/tmp/{{ zsh_awesome_font_dir }}/patched/*.ttf"

  become: yes
  become_user: "{{ local_username }}"

- name: refresh fonts cache
  shell: "fc-cache -fv"
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: check if .zshrc exists in user's home dir
      stat:
        path: "~{{ local_username }}/.zshrc"
      register: dotzshrc

    - name: backup .zshrc if it exists
      copy:
        src: "~{{ local_username }}/.zshrc"
        dest: "~{{ local_username }}/.zshrc.orig"
      when: dotzshrc.stat.exists

    - name: copy the sample .zshrc file
      copy:
        src: .zshrc
        dest: "~{{ local_username }}/.zshrc"
        force: yes
  become: yes
  become_user: "{{ local_username }}"

...
